[package]
name = "Menu_Runner_core"  # Keep same name for consistency
version = "0.1.0"
edition = "2021"

# No need for [lib] section - it will use src/lib.rs by default

[dependencies]
tokio = { version = "1.44.2", features = ["fs", "io-util"] }  # Add tokio for async file ops
