[package]
name = "Menu_Runner_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["fs", "io-util"] }
serde_json = "1.0"  # For parsing JSON menu files
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"  # Added YAML support

